FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --prod

RUN ls -alh dist/todo_app

RUN npm install -g http-server

EXPOSE 80

CMD ["http-server", "dist/todo_app/browser", "-p", "80"]
